const BASE_URL = 'http://127.0.0.1:3000';

export enum AppSettings {
  CAR_NAME_DEFAULT = '',
  CAR_COLOR_DEFAULT = '#000000',
  GARAGE_PAGE_LIMIT = 7,
  WINNERS_PAGE_LIMIT = 10,
  RANDOM_CARS_COUNT = 100,
  START_STOP_ENGINE_URL = `${BASE_URL}/engine/`,
  GET_CARS_CREATE_CAR_URL = `${BASE_URL}/garage`,
  UPDATE_DELETE_CAR_URL = `${BASE_URL}/garage/`,
  GET_WINNERS_CREATE_WINNER_URL = `${BASE_URL}/winners`,
  UPDATE_DELETE_WINNER_URL = `${BASE_URL}/winners/`,
}
